### ISSUE TITLE
Using `data_file` in EVEREST crashes after `batch_0`

### ISSUE THREAD

**Issue by roliveira** [equinor/ert#10252]
### What happened? (You can include a screenshot if it helps explain)

Adding 

```yaml
definitions:
  flow_folder: r{{configpath}}/../../flow/
# [...]
model:
  realizations: [6, 10, 31, 22, 24, 45, 50, 68, 36, 62]
  data_file: r{{flow_folder}}/model/EGG_MODEL_FLOW.DATA
```

Fails after `batch_0`.

Contents of `manifest.json` for one of the simulations:

```json
{
  "summary_eclipse/ECL.UNSMRY": "eclipse/ECL.UNSMRY",
  "summary_eclipse/ECL.SMSPEC": "eclipse/ECL.SMSPEC",
  "gen_data_npv": "npv"
}
```

### What did you expect to happen?

For a summary data to be loaded.

### steps to reproduce

```Python

```

### Environment where bug has been observed

- [ ] python 3.11
- [ ] python 3.12
- [ ] macosx
- [ ] rhel7
- [ ] rhel8
- [ ] local queue
- [ ] lsf queue
- [ ] slurm queue
- [ ] openPBS queue
