### ISSUE TITLE
In Everest scaling breaks discrete optimizers

### ISSUE THREAD

**Issue by slawekszklarz** [equinor/ert#10298]
### What happened? (You can include a screenshot if it helps explain)

The discrete optimizers expect integer values and therefore scaling makes them fail. The scaling should be disabled  when `control_type: integer` specified in the control variable section. 

To reproduce: use integer control variable, e.g.:

```YAML
  -
    name: my_control
    type: generic_control
    control_type: integer
    min: 1
    max: 11
    variables:
        - {name: my_var, initial_guess: 5}
```

and use one of the discrete optimizers, e.g.:

```YAML
optimization:
  algorithm: mads
  options:
  - BB_MAX_BLOCK_SIZE 50
```

Temporary solution was to define scaling to the same interval:

```YAML
  -
    name: my_control
    type: generic_control
    control_type: integer
    min: 1
    max: 11
    variables:
        - {name: my_var, initial_guess: 5, scaled_range: [1, 11]}
````

### What did you expect to happen?

Everest not fail when using discrete optimizer

### steps to reproduce

```Python

```

### Environment where bug has been observed

- [ ] python 3.11
- [ ] python 3.12
- [ ] macosx
- [ ] rhel7
- [ ] rhel8
- [ ] local queue
- [ ] lsf queue
- [ ] slurm queue
- [ ] openPBS queue
