### ISSUE TITLE
Remove `source` from `install_jobs` section in Everest config

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#10301]
**Is your feature request related to a problem? Please describe.**
When users have to install custom jobs, they have to add them to the `install_data`-section:
```yaml
install_jobs:
  - name: forward_model
    source: r{{configpath}}/../input/forward_model
```
where `source` points to a file, which is typically just `EXECUTABLE forward_model.exe`, but can also have some other config options.

This causes the user to have to manage extra external files.

**Describe the solution you'd like**
This should be inlined into the `install_jobs` section with no need for an external file:

```yaml
install_jobs:
  - name: forward_model
    executable: r{{configpath}}/../input/forward_model.exe
```

all the optional settings, `min_args`, `max_args` etc. should also be possible to configure here. We should be able to use the `dataclass` from ert directly, so we get the same, or better validation then we currently do.

After this change, we should still parse the deprecated `source` for a while, notifying the users that it is deprecated, and show them what the new configuration should look like, for the example above:

The `source` keyword in `install_data` is deprecated, you should instead do:
```yaml
install_jobs:
  - name: forward_model
    executable: r{{configpath}}/../input/forward_model.exe
```

Does not have to be that exactly, but something along those lines.
