### ISSUE TITLE
Remove `source` from the `install_workflow_jobs` section in the Everest config

### ISSUE THREAD

**Issue by verveerpj** [equinor/ert#10481]
**Is your feature request related to a problem? Please describe.**
Currently the `install_workflow_jobs` section is used as follows:

```yaml
install_workflow_jobs:
  -
    name: test_wf
    source: jobs/TEST_WF
``` 

**Describe the solution you'd like**
This should follow the same approach as is used by `install_jobs`:

```yaml
install_workflow_jobs:
  -
    name: test_wf
    executable: jobs/test_wf.exe
``` 

with `executable` providing the path to the executable, without the need for any intermediate config files
