### ISSUE TITLE
Add more strict validation between specified objectives/constraints and forward model results

### ISSUE THREAD

**Issue by yngve-sk** [equinor/ert#10778]
If we specify objectives or constraints, we could assert that the user has specified a forward model that produces results for that objective/constraint. These results (although they are mapped to gen_data internally) could be defined as their own types. Tentative suggestion:

```

objective_functions:
  - name: distance
forward_model:
  - job: adv_distance3 --point-file point.json --target-file data/r{{ realization}}/target.json --out distance
    results:
      file_name: distance
      type: objective
  # Expect no objective, but should generate gen_data in ERT storage
  - job: adv_distance3 --point-file point.json --target-file data/r{{ realization}}/target.json --out distance_nonobj
    results:
      file_name: distance_nonobj
      type: gen_data
```

This is more explicit and less tied to ERT internal datatypes.

https://github.com/equinor/ert/pull/10597#discussion_r2074840373
