### ISSUE TITLE
Introduce schema for main Everest configuration file

### ISSUE THREAD

**Issue by slawekszklarz** [equinor/ert#10849]
Similarly as done for forward model jobs a schema generation could be introduced to Everest. It would be useful for a quick command line keyword reference and it is also suitable for generating template Everest config file.

For example, running:
```
everest --schema
```
would generate (similar format to forward model inputs), e.g.:
```yaml
# The environment of Everest, specifies which folders are used for simulation and output, as well as the level of detail in Everest-logs
# Required: False
environment:
   # Folder used for optimization output
   # Datatype: string
   # Examples: r{configpath}/../output
   # Required: False
   output_folder: everest_output
   # Folder used for simulation by Everest
   # Datatype: string
   # Examples: r{configpath}/../output/simulations
   # Required: False
   simulation_folder: simulation_folder
   # Random seed used to generate perturbations
   # Datatype: integer, positive
   # Examples: 1,13
   # Required: False
   ranodm_seed: null
...
```
