### ISSUE TITLE
Not possible to configure everest objective file

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#10995]
### What happened? (You can include a screenshot if it helps explain)

After the recent change to the config format, I tried to configure a custom reading of the objectives file, from: https://github.com/equinor/ert/blob/80424797dec0627dbbc9fa08868f748326fed18e/test-data/everest/math_func/config_advanced.yml#L47-L51

```yaml
  - job: adv_distance3 --point-file point.json --target-file data/r{{ realization}}/target.json --out my_distance
    results:
      file_name: my_distance
      type: objective
      keys: "*"
```
not that I have changed --out -> my_distance and the file_name to my_distance

### What did you expect to happen?

I would expect this to change the required file from `distance` -> `distance_out`, but that did not happen, I got: 
```
Forward model error: Could not find one or more files/directories while reading everest_objectives: /path/to/ert/test-data/everest/math_func/everest_output/scratch/advanced/batch_0/geo_realization_2/simulation_15/distance not found.
```

### Steps to reproduce

```Python

```

### Environment where bug has been observed

- [ ] Python 3.11
- [ ] Python 3.12
- [ ] macOS
- [ ] RHEL8
- [ ] RHEL9
- [ ] Local queue
- [ ] LSF queue
- [ ] Slurm queue
- [ ] OpenPBS queue
