### ISSUE TITLE
Storage: Add '--test-fixture' option for integration-testing webviz-ert

### ISSUE THREAD

**Issue by pinkwah** [equinor/ert#1389]
Add an option called `--test-fixture=` to `ert api` which will load a pre-made database from a YAML file. I take inspiration from Ruby on Rails' text fixture system:

```yaml
ensemble:
  - id: default
    name: default
    num_realizations: 2

response_definition:
  - id: poly_res
    ensemble_id: default
    name: POLY_RES

response:
  - values: [1.0, 2.0, 3.0]
    indices: [1, 2, 3]

observation:
  - id: poly_obs
    name: POLY_OBS
    values: [1.0, 4.0, 9.0]
    errors: [0.1, 0.2, 0.3]

observation_response_definition_link:
  - observation_id: poly_obs
    response_definition_id: poly_res
```

In order to make our lives more magical, I make the following assumptions:
1. We're bypassing SqlAlchemy entirely and creating an SQL transaction from scratch
2. The outermost keys are equivalent to some SQL table name (ie, `ensemble` is a table that exists)
3. Each key is a list
4. Each element of this list is an object where each key corresponds to a _real_ column (ie, not a `sqlalchemy.relationship`)
5. The `id` column is special, in that if it's a `str`, then it's replaced with a unique `int` and placed in a mapping of names to `id`s
6. Any column that ends with `_id` is also special, in that if it's a `str`, it get replaced with the `int` from the aforementioned mapping
