### ISSUE TITLE
On steps, stages and records

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#1399]
The goal of this issue is to discuss configuration (and maybe implementation) of abstract stages and record passing.

**Context**
Let me start by highlighting some assumptions and frames for this discussion. My hope is that this will make them easier to challenge, not to write them in stone!

A _record_ is a structured data element that can be passed through the (forward model) pipeline of ERT. Currently it allows for data that can be represented as JSON. But one could imagine a richer set off data formats in the future!

A _step_ is an atomic unit in the pipeline for which one can reason about the data flow (records) going in and out. Hence, in addition to the description of the execution of a step (which is step type dependent) a step will both list the records it requires as input and the records it produces as a result.

A _unix step_ is a step for which all data is persisted in files and the logic is executed as a shell script on top of these files. Each record (both input and output) is coupled with files on a (local) disk, such that from the scripts perspective the input is present on disk and the sole purpose is to produce the output data on disk in the correct files. As unix steps are currently supported by `ert3` a concrete configuration example can be given:

```yaml
-
  name: evaluate_polynomial

  input:
    -
      record: coefficients
      location: coefficients.json

  output:
    -
      record: polynomial_output
      location: output.json

  transportable_commands:
    -
      name: poly
      location: poly.py

  script:
    - poly --coefficients coefficients.json --output output.json
```

[Note: This step is not implemented yet and hence this section is opinionated! Relevant PR: #1320]
A _function step_ is a step that consists of a single Python function. Also here the input and output records are defined up front. Notice that the function step is thought to be without side effects and hence touching disk is undefined behaviour. A suggestion for configuration would be:

```yaml
-
  name: evaluate_polynomial
  type: function # <-- Since we now gave two different step types they should probably be explicit about their type
  input:
    -
      record: coefficients
      location: coeffs
    -
      record: x
      location: x

  output:
    -
      record: polynomial_output
      location: output

  function: my_functions.polynomials:second_degree_polynomial
```

where

```python
def second_degree_polynomial(coeffs, x):
     x = np.array(x)
     a, b, c = coeffs["a"], coeffs["b"], coeffs["c"]
     return {"output": list(a * x ** 2 + b * x + c)}
```

**The stage**
A stage allows for up-front reasoning about input and output records. As of such, all steps are stages. But, in addition to the steps we want to introduce a stage entity that allows to describe the data flow between stages. I don't have a good naming suggestion as of now, but `abstract stage`, `flow stage`, `data stage` or something similar might be considered? Until a name is decided I suggest we stick to `flow stage`. Notice that a `flow stage` is a `stage` and will hence again have to be explicit about its input and output records. But in addition we would like it to be able to pass output records of one stage as input records to another stage.

Given two stages `f` and `g` where `f` takes the input records `u` and `v` and produces `w` and `g` takes `x` as input and produces `y` and `z`. That is `f : u, v -> w` and `g : x -> y, z` for some notation. I then want to make a flow stage `h` that takes as input `m` and `n` produces `p` and `q` by first evaluating `my_w = f(u=m, v=n)` followed by `my_y, my_z = g(x=my_w)` and returning `p=my_y` and `q=my_z`.

**Questions**
- Do we agree on the assumptions?
- Do we agree upon the stage definition?
- If so, how do we want to configure a flow stage?

Since Python is our default language I would suggest that the flow stage feels a bit like a list of Python statements. Perhaps we could even more or less copy the Prefect syntax?
