### ISSUE TITLE
Index distributions

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#1436]
Currently one must specify the name of each of the variables in a parameter group. However, both distributions and records (after https://github.com/equinor/ert/pull/1415) is ready for also passing arrays or indexed distributions. Hence, we could make it possible to not give the variable names, but instead only configure the length of the vector.

**Comment by markusdregi** [comment]
Currently, a key-value parameter group is configured as:

```
-
  name: coefficients
  type: stochastic
  distribution:
    type: gaussian
    input:
      mean: 0
      std: 1
  variables: ["a", "b", "c"]
```

The array could be configured something along the lines of:

```
-
  name: coefficients
  type: stochastic
  distribution:
    type: gaussian
    input:
      mean: 0
      std: 1
  size: 10
```

which would give an array of sampled parameters of length 10.
