### ISSUE TITLE
Individual distribution per variable

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#1437]
Make it possible to assign different distribution types and distribution arguments to different variables within the same parameter group. This probably only makes sense for key-value groups as part of the `variables` definition.

**Comment by berland** [comment]
The situation with todays parameter configuration is that for snake_oil (a future pull request), one needs the following in `stages.yml` (only shown for the OP1-parameters):

```yaml
  input:
    - record: op1_persistence
      location: op1_persistence.json
    - record: op1_octaves
      location: op1_octaves.json
    - record: op1_divergence_scale
      location: op1_divergence_scale.json
    - record: op1_offset
      location: op1_offset.json
```

In `parameters.yml`, one section for each of these looking like:
```yaml
-
  name: OP1_PERSISTENCE # e.g. group name
  distribution:
    input:
      lower_bound: 0.01
      upper_bound: 0.4
    type: uniform
  variables:
  - OP1_PERSISTENCE
  type: stochastic
```
where there is a 1-1 between parameter groups and parameter names (necessary because we need to vary distribution parameters within each group).

Each parameters must then be listed in `experiments/evaluation/ensemble.yml` 
```yaml
input:
  -
    source: stochastic.OP1_PERSISTENCE
    record: op1_persistence
  -
    source: stochastic.OP1_OCTAVES
    record: op1_octaves
  -
    source: stochastic.OP1_DIVERGENCE_SCALE
    record: op1_divergence_scale
  -
    source: stochastic.OP1_OFFSET
    record: op1_offset
```

(one record pr parameter). For snake_oil, with some legacy parameters.txt routines, the final point where we must mention each parameter is in `resources/snake_oil.txt.tmpl`:
```
OP1_OFFSET:{{op1_offset.OP1_OFFSET}}
```

In runpath, we are left with one json file for every parameter.

**Comment by berland** [comment]
Is there a user story for the need for "multiple variables with the same distribution parameters grouped as a parameter group"?

**Comment by markusdregi** [comment]
This should definitively be supported. I guess the current support is more a result of ease to implement more than a specific user need...

**Comment by berland** [comment]
#2224 should be merged prior to this.

**Comment by berland** [comment]
Central to how to resolve the underlying problem is the role of a single `NumericalRecord`. 

* Should it represent "one thing", where "one thing" might be a single multipler. This is #2908 
* Should a single NumericalRecord be able to represent grouping of related multipliers/parameter, or does a grouping
hierarchy belong elsewhere? This is essentially what the `variables` concept gives today, but constrained to identical distributions.
* How should parameter groups with "one" member be treated? Like a model parameter that is not naturally grouped with anything, should it have a dummy group name, and the real parameter name encoded in the `variables` section?

The "underlying" problem is perhaps the connection from `parameters.yml` to json files dumped to runpath and jinja templating. Todays solution (e.g. snake oil in ert3) give a multitude of json files that in practice requires globbing when rendering. It might not be correct to solve that problem by changing how parameters are configured.

**Comment by berland** [comment]
Implementing individual distributions pr. variable induces a problem with parameters defined with `size` instead of `variables`, as then the `distribution` must be moved from class `_ParameterConfig` in 
https://github.com/equinor/ert/blob/main/ert3/config/_parameters_config.py#L147_L157
into `_VariablesConfig`. But only if `size` is not in use, if so, then it should stay put.

This is probably possible in Pydantic with discriminated unions, but may not be a pretty solution.

**Comment by berland** [comment]
A future user request will be to add a string values in parameters, coming from e.g. a discrete distribution. The user might think like this in `parameters.yml`:
```
- 
  name: permeability_stuff
  type: stochastic  
  variables:
    perm_scenario:
      type: discrete
      values:  ["poro_formula", "petrophysics_interpretation"]
    perm_multiplier:
      type: loguniform
      lower_bound: 0.1
      upper_bound: 10
```
