### ISSUE TITLE
Constant uniform distribution in SPE1 example

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#1698]
**Introduction**
The SPE1 setup is leveraging that a uniform distribution can have lower_bound == upper_bound. This is a bad way of communicating the intent of constant data! https://github.com/equinor/ert/pull/1650 first attempted to enforce `lower_bound < upper_bound`, but this was abandoned due to the then necessary changes to the SPE1 setup that was deemed out of scope at that moment.

**Suggested approaches**
I suggest that we resolve this either by introducing a constant distribution or by passing the constant data as a non-sampled record directly from disk. The first requires us to implement a constant distribution, while the later requires us to make the sensitivity algorithm capable of dealing with non-sampled records (currently it asserts that all records stems from `parameters.yml`). Both are sensible steps forward that we should do at one point, but either is sufficient for improving the current SPE1 example.

**Definition of done**
The SPE1 example still contains constant data and there is a test verifying that `lower_bound == upper_bound` for a uniform distribution gives an error in the parameter config tests.

**Comment by joakim-hove** [comment]
> I suggest that we resolve this either by introducing a constant distribution

There is a `CONST` distribution.

**Comment by markusdregi** [comment]
I know @joakim-hove :) But, distributions are part of the logic not currently merged between ert2 and ert3. It should definitely be so, but in the meantime it would be neat to keep the examples as neat as possible...

**Comment by BjarneHerland** [comment]
Would something like this make sense from a "neat and clear config perspective"?

```
  name: wells_no_delay
  type: stochastic
  distribution:
    type: constant
    input:
      value: 1
  variables: ["delay"]
```

or perhaps  more generally

```
  name: wells_no_delay
  type: stochastic
  distribution:
    type: uniform
    input:
      valueset: [1]
  variables: ["delay"]
```

where the latter should sample uniformly from a set of given values, in this case only 1's  (Somewhat like DUNIF in ERT2, but with a more flexible way to specify the distribution. for example would  `valueset: [0 1 1 1 2] ` sample 1's three times more often than 0's or 2's.)
