### ISSUE TITLE
Make Github actions run on pull_request and on push to main and version-*

### ISSUE THREAD

**Issue by sondreso** [equinor/ert#1739]
Currently Github actions will run on both the pull_request event and push to all branches. This causes all workflows to run twice if you push to a branch on the upstream repo that also has a pull request open. We should change our triggers to something like this: 

```
on:
 push:
   branches:
     - main
 pull_request:
```

But should probably also include version branches.
