### ISSUE TITLE
Easier experimentation with x-values in the ERT3 polynomial example

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#1853]
**Context**
Currently the x-values evaluated in the polynomial example for ERT3 is hard-coded to `[0, 1, ..., 9]`. However, it would be neat to change the setup such that the user easily can provide their own values x-values to be evaluated instead.

In addition, in https://github.com/equinor/ert/pull/1835 numerical array records where introduced which led to the added example of perturbing the x-values according to a distribution.

**Suggestion**
Make the `x`-values in the example explicit by treating them as a constant record that is passed to the forward model instead of being hard-coded within the polynomial script.

This also makes it possible to make `poly.py` unaware that the x-values are potentially perturbed as seen in #1835. Instead, with the x-values in a record and hence on disk when running, we can split the responsibility such that the stage first adds the uncertainties to the x-values already residing in a file on disk and then afterwards we run `poly.py`.

**Examples**
First, I would like to introduce an example that runs with a different set of x-values without having to change the logic of the stages.

Second, we could then see the stage in #1835 change to something along the lines of:

```yml
-
  name: evaluate_x_uncertainty_polynomial
  input:
    -
      record: coefficients
      location: coefficients.json
    -
      record: x
      location: x.json
    -
      record: x_uncertainties
      location: x_uncertainties.json
  
  output:
    -
      record: polynomial_output
      location: output.json
  
  transportable_commands:
    -
      name: poly
      location: poly.py
    -
      name: json_sum
      location: json_sum.py

  script:
    - json_sum --output x.json --input x.json x_uncertainties.json 
    - poly --coefficients coefficients.json --values x.json --output output.json
```

Notice that the step would function also if we remove `json_sum`, making `poly` unaware of the manipulation of the input. Which is how this kind of modelling is often done, as modifying the simulator itself is both unwanted and not possible.
