### ISSUE TITLE
Allow the user to recover from providing numerical data ert does not understand

### ISSUE THREAD

**Issue by jondequinor** [equinor/ert#1958]
**Describe the bug**

I provide the record config:
```
name: my_evaluation
input:
  -
    record: coefficients
    location: coefficients.hdf5
```

Firstly, how and what do we communicate to the user that

1. ert doesn't know what to do with this file
2. ert needs to change in order for the numerical data in this file to be loaded

Secondly, how do we separate this from e.g.

```
name: my_evaluation
input:
  -
    record: some_template
    location: my_template.jinja2
```

Where this is obvious to humans to not be numerical data, but maybe not to ert.

I think this is mainly me being confused.
