### ISSUE TITLE
Allow NumericalRecordTree as an ouput record in ensemble config

### ISSUE THREAD

**Issue by xjules** [equinor/ert#2698]
Instead of writing down individual sub-records contained within a RecordTree, the output in the ensemble.yml should refer to them only via the RecordTree name and should populate the responses automatically for each contained sub-record.
Example:
Instead of:
```yml
output:
  -
    record: FOPT
  -
    record: FOPR
 ...
```
should be enough to write:
```yml
output:
    - record: summary_record
```
