### ISSUE TITLE
Introduce scalar NumericalRecord

### ISSUE THREAD

**Issue by berland** [equinor/ert#2908]
This feature proposal represent an alternative to #1437 .

If both `variables` and `size` is missing in one entry in `parameters.yml` , the record type should be a new type `SCALAR_FLOAT`. The aim is to be able to define a parameter like this:
```
- name: PORO_MULTIPLIER
  type: stochastic
  distribution: uniform
    input:
      lower_bound: 0.8
      upper_bound: 1.2
```

A sub-issue is then to make it possible to render this using jinja2 templating as
```
PORO_MULTIPLIER:{{parameters.PORO_MULTIPLIER}}
```
(this rendering example recreates the ERT2 "`parameters.txt`"). The namespace `parameters` could be a default namespace making anything in `parameters.yml` available to the (default) rendering script. How to connect jinja templating namespaces with NumericalRecord(s) and/or RecordTree can be seen as an implementation detail. 

Scalar records might imply a higher overhead. A mitigating factor could be to handle them through RecordTrees.
