### ISSUE TITLE
Add support for log-uniform distribution in ert3

### ISSUE THREAD

**Issue by berland** [equinor/ert#2925]
**Is your feature request related to a problem? Please describe.**
Make it possible to model parameters with a log-uniform distribution in ert3, similar to LOGUNIF in ert2.

**Describe the solution you'd like**
Make it possible to write:

```
- name: my_fault_multiplier
  type: stochastic
  distribution:
    type: loguniform
    input:
      lower_bound: 0.00001
      upper_bound: 0.1
```

**Additional context**
General distribution support issue:  #1458
