### ISSUE TITLE
User story for grouping of parameters in ert3

### ISSUE THREAD

**Issue by berland** [equinor/ert#3114]
As a user, I need to be able to group parameters and use the grouping for something sensible.

Parameters are here each item in `parameters.yml`.

If I don't want to set up grouping yet, there should be a global implicit group.

When specifying steps, I want to be able to use the grouping to state which records go in an out from a step, in order to save typing.

Since a record may have overlapping usage, say a water-oil-contact that is input to both RMS and Eclipse, a record must be able to belong to multiple groups.

When doing templating, the group structure should be optional to use. This means that for the abovementioned water-oil-contact "`woc`", three possible json paths are thinkable, `woc`, `eclipse.woc`, `rms.woc`, and they all render to the same float.

I need to be able to reuse a parameter name when it belongs to distinct groups, say for example `well_length` should be possible as a parameter name in groups `op1` and `op2`, being two unique parameters. 

I would like validation of template files as early as possible.

**Comment by lars-petter-hauge** [comment]
A possible way of configuring groups in the `parameters.yml` file could be to create the groups and referring to the parameter names. As opposed to specifying which groups a parameter belongs to within each specification of a parameter. Here I have created both configurations:

Specify group within parameter
```
- name: A
  type: stochastic
  group: ["Group_A-B"]
  distribution:
    type: gaussian
    input:
      mean: 0
      std: 1
- name: B
  type: stochastic
  group: ["Group_A-B", "Group_B-C"]
  distribution:
    type: gaussian
    input:
      mean: 10
      std: 1
- name: C
  type: stochastic
  group: ["Group_A-B"]
  distribution:
    type: gaussian
    input:
      mean: 100
      std: 1
```


Separate group specification:
```
parameters:
  - name: A
    type: stochastic
    distribution:
      type: gaussian
      input:
        mean: 0
        std: 1
  - name: B
    type: stochastic
    distribution:
      type: gaussian
      input:
        mean: 10
        std: 1
  - name: C
    type: stochastic
    distribution:
      type: gaussian
      input:
        mean: 100
        std: 1
groups:
  - name: Group_A-B
    parameters: ["A", "B"]
  - name: Group_B-C
    parameters: ["B", "C"]
```

Given that the user will refer to using e.g. "Group_A-B" in their `ensemble.yml`, it looks easier to figure out the content of said group with the configuration of defining groups in their separate section. Adding a new group would also be easier with the latter configuration, as you would only need to specify the group content in a single entry.
