### ISSUE TITLE
Change entry record -> name in ensemble.yml

### ISSUE THREAD

**Issue by lars-petter-hauge** [equinor/ert#3337]
The work in https://github.com/equinor/ert/pull/3025 changed the `stages.yml` configuration

From:

```
   input:
     -
       record: coefficients
       location: coefficients.json

```
To:

```
   input:
     -
       name: coefficients
       transformation:
         type: serialization
         location: coefficients.json
```

The change from `record` to `name` should also be reflected in `ensembles.yml`. An additional suggested change is to explicitly specify `stage_input` instead of just `input` to clarify what is configured. Suggest changing 

From:

```
input:
  -
    source: stochastic.coefficients
    record: coefficients
```

To:

```
stage_input:
  -
    source: stochastic.coefficients
    name: coefficients
```

Note that the concept of `record` still exists for the user both in documentation and when using `ert3 load record` on the command line
