### ISSUE TITLE
Enable user to make workflows launchable through buttons in GUI

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/ert#371]
Make user able to elevate selected workflows in a way that makes them launchable through a button in the GUI.

Details:
Workflows are today listed in the dropdown. The user must open the dropdown, select workflow, then press play. This does not scale well when the number of workflows is high. Some order in the list can be induced by carefully naming the workflows. When having many hooked workflows, these also clutter the list.

In reality, a large fraction of the workflow usage boils down to a low number of workflows. I would like the ability to elevate some workflows to a specific button in a separate band in the GUI. The user would click the button to launch the workflow, rather than finding/selecing the workflow in the dropdown, then clicking play.

The dropdown could remain as today. Buttons could come in addition.

I picture this being induced by the user through the config:
```
LOAD_WORKFLOW   ../bin/workflows/MyWorkflow
BUTTON_WORKFLOW MyWorkflow
```

...or something like that.

**Comment by markusdregi** [comment]
Thank you for the input @perolavsvendsen! I think it is a great idea to put some concept on top of the long list of workflows.

However, I don't think we are quite in a state where we should enable buttons in the GUI via the config file yet. We have to many moving pieces in the code, as well as in the GUI itself. What I would suggest is to add the concept of a `stage` to the workflows. Could then do something like:

```yaml
install_workflows:
  - source: ../bin/workflows/my_workflow

workflow_stages:
  postprocessing:
    - massage_eclipse_data
    - load_data_to_cloud
  my_special_stage:
    - my_workflow
    - some_other_worklow
```

and then you would be presented with the list of stages in the GUI and you could quickly select the stages you want to execute (i.e. `my_special_stage`) and run them. Lets go to `yaml` first, and then I'll give you a :carrot: to move besides the nicer format :+1:
