### ISSUE TITLE
Implement POC for yaml ERT project

### ISSUE THREAD

**Issue by markusdregi** [equinor/ert#487]
Create a POC of yams-configuration, as well as a project concept in ERT. Load `project`-configurations, as well as `experiment`-configurations, internalise observations and parameters. The format for parameters into the forward model and results out again should be standardised (alternatives include but are not limited to: unix-style files, JSON, numpy format).

This will include writing schemas for the below configuration files, as well as doing the translation between the old and the new configurations to ensure that observations etc can be loaded.

```yaml
# project.yml

install_jobs:
  -
    name: poly_eval
    script: ../../bin/poly_eval.py

stages:
  -
    name: evaluate
    jobs:
      - poly_eval

model:
  realizations: [0-99]

queue_system:
  default_driver: local
  local:
    max_submit: 50
```

```yaml
# prior/config.yml

experiment:
  name: poly_prior
  parameters:
    - coeffs

environment:
  simulation_folder: ../../scratch
  output_folder: ../../output

install_data:
  -
    source: ../../data/data_points
    target: data_points

forward_model:
  - evaluate

results:
  -
    name: poly_res
    type: array
    file: poly.out
```

```yaml
# posterior/config.yml

update:
  algorithm: ensemble_smoother
  prior: poly_prior
  posterior: poly_posterior
  match:
    -
      observation: poly_obs
      measurement: poly_res

environment:
  simulation_folder: ../../scratch
  output_folder: ../../output

install_data:
  -
    source: ../../data/data_points
    target: data_points

forward_model:
  - evaluate

results:
  -
    name: poly_res
    type: array
    file: poly.out
```

```yaml
-
  name: coeffs
  type: array
  variables:
    -
      name: a
      distribution: uniform
      min: 0
      max: 1
    -
      name: b
      distribution: uniform
      min: 0
      max: 2
    -
      name: c
      distribution: uniform
      min: 0
      max: 5
```

```yaml
-
  name: poly_obs
  type: array
  observations:
    -
      value: 2.8532509308
      std: 0.1
    -
      value: 7.20311703432
      std: 1.1
    -
      value: 21.3864899107
      std: 4.1
    -
      value: 31.5145559347
      std: 9.1
    -
      value: 53.5676660405
      std: 16.1
```
