### ISSUE TITLE
MPI Setup for ERT and Flow Simulator

### ISSUE THREAD

**Issue by GSchnoeller** [equinor/ert#8379]
Hi,
I am running ERT with the Flow simulator using TOQUE and 6 CPUs in the configuration. I understand that it is necessary to configure the MPI parameters in the flow_config.yml file for this setup.
Could you please tell me which keys and values need to be configured for MPI in this file?

```yaml
default_version: default
versions:
  default:
    scalar:
      executable: /path/to/flow/bin/flow
```

Do you have any examples?

Thank you for your assistance!

**Comment by GSchnoeller** [comment]
I found that it is necessary to include the flow and mpirun path as values ​​in the mpi key. I was able to use mpi with the configuration below. I will close the issue, as the problem has been resolved.

```yaml
default_version: default
versions:
  default:
    scalar:
      executable: /path/to/flow/bin/flow
    mpi:
      executable: /path/to/flow/bin/flow
      mpirun: /path/to/bin/mpirun
```
