### ISSUE TITLE
When setting install_data to a non existing directory, root partition is being copied instead

### ISSUE THREAD

**Issue by slawekszklarz** [equinor/ert#9071]
### What happened? (You can include a screenshot if it helps explain)

Related to Everest and ERT, when no variable is defined in Everest, the whole root directory (`/`) is being copied to each simulation directory.

```yaml
install_data:
  - link: False
    source: r{{ does_not_exist }}/
    target: tmp
```

### What did you expect to happen?

An error e.g.:  "does_not_exist variable does not exist." 

### steps to reproduce

Use in Everest config:

```yaml
install_data:
  - link: False
    source: r{{ does_not_exist }}/
    target: tmp
```

### Environment where bug has been observed

- [ ] python 3.8
- [ ] python 3.9
- [ ] python 3.10
- [x] python 3.11
- [ ] python 3.12
- [ ] macosx
- [ ] rhel7
- [ ] rhel8
- [x] local queue
- [ ] lsf queue
- [x] slurm queue
- [ ] openPBS queue
