### ISSUE TITLE
Align the queue config keywords with the keywords from ert

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#9611]
The queue options in ert were recently refactored to support generic queue options to abstract over the different queue options. Currently the `simulation` section contain a lot of slurm and lsf keywords that exclusive to a certain queue system, but also supported by the other, for example the: `max_memory` option, which is only supported by slurm.

All generic queue options should be placed under `simulator´, while options only supported by a single queue system should be in a sub section, for example:

```yaml
simulator:
    max_memory: 10 mb
    resubmit_limit: 1
    slurm_options:
        queue_executable: ...
    lsf_options:
        server: ...
```

this should be done with as little duplicated code between everest and ert as possible.
