### ISSUE TITLE
Support max_memory keywords also for LSF

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#9613]
**Issue**
As a user I would like to be able to do memory allocation on the compute cluster without intimate knowledge of the commands necessary for LSF.

**Definition of done**
Memory allocation on compute nodes can be done directly via configuration keywords.

```yaml
simulator:
  queue_system: lsf
  max_memory: 15000
```
