### ISSUE TITLE
Context validation of the simulator specific keywords

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#9615]
Currently there is some confusion about the validation of the `datafile`, `wells` and the `eclbase` (concept), which should be improved. In the future we might want to split all reservoir simulator specific into a new section of the configuration file.

Some background:
> To balance between the reservoir specific tooling in Everest and its general purpose capabilities we need a sane way to detect whether this is indeed a reservoir setup or not 🤷 Currently that is done by checking for the datafile key in the configuration. This decision can probably be documented and communicated better... It can also be discussed whether is should be changed.
>
>Even an empty datafile will today result in all field keywords being internalized. And if wells are added in the wells section they will be internalized as well. But to have some kind of "toggle" for activating the reservoir stuff makes a lot of sense to me at least...

Reply:

> If Everest is given an empty datafile Everest will not fail it will only internalize the default keys, or at least try to do it and fail if also there is is no wells section defined.
>
> For now, would it be acceptable either:
>
> To assume that if a wells section is present in the config file we are dealing with a reservoir setup.
    Have an actual flag in the config file that needs to be toggled to internalize any keys.
    Keep things as they are now and just document it better, even though currently there is a Note in the Everest documentation that explains that without the datafile there will be not well or group specific summary keys internalized

**Comment by oyvindeide** [comment]
One suggestion is a new section in the config file dealing with internalizing of data, for example:
```yaml
responses:
   summary:
     file_name: { flowbase }
     keys: [WOPR, FOPR, ...]  # <- could also have some defaults here like we do today
```

**Comment by yngve-sk** [comment]
^Looks flexible and less cryptic to me at least. 

Would this open for having forward models output some `gen_data` without it necessarily being a constraint/objective? (if that is something users would want). For `gen_data` we currently implicitly save all of them, so our "current" gen data default would be something like this? (assuming we omit report steps etc)
```
   gen_data:
      keys: { r{{objectives}}, r{{constraints}} }
```
Implicitly we would say that the file names are the same as `keys` in this case, which is what we do in `everest_to_ert` currently:
```
    for name in objectives_names + constraint_names:
        gen_data.append((name, f"RESULT_FILE:{name}"))
```
so the `file_name`/`input_files` would be a no-op for gendata, which is OK I guess?

Some smaller things: 
Would it make sense to put it under the model_config section? Or maybe call it `forward_model_responses` in the main config section. 

Would maybe do `input_file`/`input_files` instead of `file_name`, same as in ERT response configs.

**Comment by oyvindeide** [comment]
> Would this open for having forward models output some gen_data without it necessarily being a constraint/objective? (if that is something users would want). For gen_data we currently implicitly save all of them, so our "current" gen data default would be something like this? (assuming we omit report steps etc)

Yes, it would, if we add something like `csv_response`, or `rft` in ert, we could also load that from everest

**Comment by oyvindeide** [comment]
Refined my suggestion a bit:

```yaml
model:
  realizations: [6, 10, 31, 22, 24, 45, 50, 68, 36, 62]
  results:
    - type: summary
      summary_file: r{flowbase}
      keys:  # <- Optional
        - WOPR:INJECTOR_1
        - FOPR
        - W*:*
    - type: csv
      file_name: my_result.csv
    - type: gen_data
      file_name: results.txt
```

**Comment by oyvindeide** [comment]
There is of course the option of configuring it under the `forward_model`, but might be too much data to add there:
```yaml
forward_model:
  - ...
  -   - flow  r{{flowbase}}.DATA --keys: W*,F*
```
but then it would only work for pre-configured forward models, and a forward model producing summary files that was not in our list of forward models would not work.

**Comment by yngve-sk** [comment]
I think the list makes sense, if we have multiple gendatas/csvs we just have more list items. Adding response info to forward model args would be nice but also seems too verbose as you say. 

When we add gendata we only need to give the filename, without any substitutions as in your example? 

If we want to copy the `data_file` to runpath (also wondering a bit why this couldn't just be `install_data`? I feel I've seen cases of install_data used for this..), how do we match them up? If `data_file` is `eclipse/r{{geo_id}}/TEST.DATA`, what would the  `model.results[0].summary_file`?

**Comment by oyvindeide** [comment]
> I think the `model.results` list makes most sense, if we have multiple gendatas/csvs we just have more list items. Adding response info to forward model args would be nice but also seems too verbose as you say.
> 
> When we add gendata we only need to give the filename, without any substitutions as in your example?

The objectives would still be added under the hood I think, as that is probably explicit enough for users.

> If we want to copy the `data_file` to runpath (also wondering a bit why this couldn't just be `install_data`? I feel I've seen cases of install_data used for this..), how do we match them up? If `data_file` is `eclipse/r{{geo_id}}/TEST.DATA`, what would the `model.results[0].summary_file`?

Maybe the `data_file` keyword should go away, seems it not apparent to any of our users how that is actually used, and they do copy it in the `install_data` section, it is not done automatically by anything else, see [here](https://github.com/equinor/everest-spe-rsc-2025/blob/main/data/egg/everest/model/egg.yml) for example:

```yaml
install_data:
  - link: False
    source: r{{flow_folder}}/include
    target: flow/model/include
  - link: False
    source: r{{flow_folder}}/model/EGG_MODEL_FLOW.DATA
    target: r{{flowbase}}.DATA
```

we could probably default summary loading to * if `keys` are not specified, and document how they can make it load just well data for example.

**Comment by oyvindeide** [comment]
Or perhaps we should be even more radical, and change the `forward_model` _and_ `install_data` section? For reading data:
```
forward_model:
  - ...
  - name: flow #  <- system installed forward model, does not need executable 
    arguments:  r{{flowbase}}.DATA
    results:
      file_name: r{{flowbase}}
      type: summary
      keys:  # <- Optional, defaults to *
        - F*
        - W*
  - name: forward_model #  <- custom forward model, needs executable 
    executable: r{{configpath}}/../input/forward_model.py
    arguments: --input coordinates.json --output objective
```

The first example is modified from: https://github.com/equinor/everest-spe-rsc-2025/blob/main/data/egg/everest/model/egg.yml


The second from: https://github.com/equinor/everest-spe-rsc-2025/blob/main/data/simple/everest/model/simple.yml, which would drop the `install_data` section

**Comment by yngve-sk** [comment]
I think I would find this easier to follow as a user at least. It would also open for specifying dependencies between forward models, or files it expects to exist before running etc etc, overall I think this would be better to work with as a developer.

I agree the `data_file` is confusing especially alongside having options to use `install_data` and `eclbase`. To me it would seem sensible to specify the `install_data` per forward model, but maybe also keep the option to have a "global" one? Would be to basically just have an `InstallDataConfig` field for every `ForwardModelStepConfig`

**Comment by oyvindeide** [comment]
>  To me it would seem sensible to specify the install_data per forward model, but maybe also keep the option to have a "global" one? Would be to basically just have an InstallDataConfig field for every ForwardModelStepConfig

Yes, think that might solve a few problems, and make everything more explicit.

**Comment by slawekszklarz** [comment]
Loading custom `gen_data` is useful. In the past we used a workaround to track some non-optimized quantities by placing them as objective with weight close to 0, but this is dangerous as it might still impact optimizer. 

For merging forward model perhaps drop some keys for simplicity? These are usually already known standards to provide arguments.

```yaml
simulation_jobs:
  - ...
  - job: flow r{{flowbase}}.DATA
    results:
      file_name: r{{flowbase}}
      type: summary
      keys:  # <- Optional, defaults to *
        - F*
        - W*
  - job: r{{configpath}}/../input/forward_job.py --input coordinates.json --output objective
```
Key names can be debated, I think _model_ tends to be interpreted as a numerical/geological model rather than calculation of something. 

The `install_data` is also used to copy/link directory/files that are not explicit arguments to a forward job, e.g. simulator's include directories which are different per realization. But on the other hand it is still specific to a forward job.

**Comment by oyvindeide** [comment]
We could allow a hybrid of old and new style I think without  it being horrible, something like:

```yaml
simulation_jobs:
  - ...
  - job: flow r{{flowbase}}.DATA
    results:
      file_name: r{{flowbase}}
      type: summary
      keys:  # <- Optional, defaults to *
        - F*
        - W*
  - r{{configpath}}/../input/forward_job.py --input coordinates.json --output objective
```

we could parse the `name` from `job`, but might be even better to be explicit? So:

```yaml
simulation_jobs:
  - ...
  - name: flow
    arguments: r{{flowbase}}.DATA
    results:
      file_name: r{{flowbase}}
      type: summary
      keys:  # <- Optional, defaults to *
        - F*
        - W*
  - r{{configpath}}/../input/forward_job.py --input coordinates.json --output objective
```

**Comment by roliveira** [comment]
For the reservoir simulator job, I can imagine the two following usage patterns:

1. One user trying to specify all possible entries for the `results` section because of one particular non-standard key, or the need of only a few keywords:
 
```yaml
- name: flow
    arguments: r{{flowbase}}.DATA
    results:
      file_name: r{{flowbase}}
      type: summary
      keys:
        - F*
        - SOME_SPECIAL_KEYWORD
```

2. Using the defaults for most if not all of the results section:

```yaml
- name: flow
    arguments: r{{flowbase}}.DATA
    results:
      file_name: r{{flowbase}}  # optional, default to job[arguments] ...
      type: summary             # optional, default to summary if job[name]==flow?
```

This would eventually make the results section optional for `flow` but implicitly defined.

**Comment by roliveira** [comment]
Can I assume that this could be extended for other cases like this (poorly made) example:

```yaml
- name: well_trajectory
    # [...]
    results:
      file_name: well_trajectory_input.yml
      type: csv  # or a custom format?
```

And perhaps we could implement the `results` entry for a few of the the relevant forward models.
