### ISSUE TITLE
Using yaml files within yaml files (!include directives)

### ISSUE THREAD

**Issue by oyvindeide** [equinor/ert#9617]
**Issue**
As a user I would like to include a YAML file inside an Everest config file (YAML) to simplify complex setups that contains several and repetitive controls or constraints. Although this is not defined in the current [specs of YAML](https://yaml.org/spec/1.2.2/), there are libraries that provides the directive ([pyyaml-include](https://github.com/tanbro/pyyaml-include)).

**Definition of done**
When there is an `!include` directive that allows inclusion of files as:

```yaml
generic_parameters: !include example_parameters.yaml
```

Which should eventually be rendered as:

```yaml
generic_parameters: 
    parameter1:  123
    parameter2: "abs"
    parameter3:  456
```
